### ISSUE TITLE
Dockerfile/build broken

### ISSUE THREAD

**Issue by j4ys0n** [paritytech/parity-bitcoin#541]
To reproduce:

Install docker-ce.

`git clone https://github.com/paritytech/parity-bitcoin.git`

`cd parity-bitcoin/docker/ubuntu`

`docker build -t pbtc .`

```
error: could not find `Cargo.toml` in `/build/parity-bitcoin` or any parent directory
The command '/bin/sh -c cargo build --release --verbose' returned a non-zero code: 101
```

fix:
`cp parity-bitcoin/docker/ubuntu/Dockerfile parity-bitcoin/`

**Comment by thackerronak** [comment]
Still getting error

`error[E0433]: failed to resolve. Use of undeclared type or module `keys`
   --> rpc/src/v1/impls/raw.rs:182:30
    |
182 |          Network::Mainnet => keys::Network::Mainnet,
    |                              ^^^^ Use of undeclared type or module `keys`

error[E0433]: failed to resolve. Use of undeclared type or module `keys`
   --> rpc/src/v1/impls/raw.rs:183:15
    |
183 |          _ => keys::Network::Testnet,
    |               ^^^^ Use of undeclared type or module `keys`

error: aborting due to 2 previous errors

error: Could not compile `rpc`.

Caused by:
  process didn't exit successfully: `rustc --crate-name rpc rpc/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C debuginfo=2 -C metadata=21c1a6442cbca31f -C extra-filename=-21c1a6442cbca31f --out-dir /build/parity-bitcoin/target/release/deps -L dependency=/build/parity-bitcoin/target/release/deps --extern chain=/build/parity-bitcoin/target/release/deps/libchain-636514d4793b1536.rlib --extern script=/build/parity-bitcoin/target/release/deps/libscript-2618ca4d3c2260b4.rlib --extern primitives=/build/parity-bitcoin/target/release/deps/libprimitives-1c742a3365e430aa.rlib --extern verification=/build/parity-bitcoin/target/release/deps/libverification-de585a2092411777.rlib --extern keys=/build/parity-bitcoin/target/release/deps/libkeys-514ed44d02457d6c.rlib --extern sync=/build/parity-bitcoin/target/release/deps/libsync-52eb2ec309cf8129.rlib --extern tokio_core=/build/parity-bitcoin/target/release/deps/libtokio_core-f30aaf5f4c97ac35.rlib --extern serde_json=/build/parity-bitcoin/target/release/deps/libserde_json-6f54679d1af416de.rlib --extern log=/build/parity-bitcoin/target/release/deps/liblog-704fe21184332aa2.rlib --extern serialization=/build/parity-bitcoin/target/release/deps/libserialization-30bff3cd12de08f7.rlib --extern jsonrpc_http_server=/build/parity-bitcoin/target/release/deps/libjsonrpc_http_server-684f673c50d4a57e.rlib --extern db=/build/parity-bitcoin/target/release/deps/libdb-b7d89b158b0c88b1.rlib --extern storage=/build/parity-bitcoin/target/release/deps/libstorage-09cd6cbcb66b16b0.rlib --extern jsonrpc_core=/build/parity-bitcoin/target/release/deps/libjsonrpc_core-4297cd6c90e840f9.rlib --extern serde=/build/parity-bitcoin/target/release/deps/libserde-1930de0acb4c1d60.rlib --extern network=/build/parity-bitcoin/target/release/deps/libnetwork-403235939964f0c7.rlib --extern rustc_hex=/build/parity-bitcoin/target/release/deps/librustc_hex-f8ea801bfc75151d.rlib --extern miner=/build/parity-bitcoin/target/release/deps/libminer-936f6e0a6331662b.rlib --extern jsonrpc_macros=/build/parity-bitcoin/target/release/deps/libjsonrpc_macros-bdfa425291ba158a.rlib --extern serde_derive=/build/parity-bitcoin/target/release/deps/libserde_derive-ba70de5a07aa7671.so --extern p2p=/build/parity-bitcoin/target/release/deps/libp2p-004cd8ffae8412a7.rlib -L native=/build/parity-bitcoin/target/release/build/rust-crypto-fe99a3ff8d8d8027/out -L native=/build/parity-bitcoin/target/release/build/rocksdb-sys-77b331fc34cc0a3c/out -L native=/build/parity-bitcoin/target/release/build/rocksdb-sys-77b331fc34cc0a3c/out -L native=/build/parity-bitcoin/target/release/build/eth-secp256k1-ed54e438f5920933/out` (exit code: 101)
The command '/bin/sh -c cargo build --release --verbose' returned a non-zero code: 101
You have new mail in /var/mail/ubuntu
`

**Comment by General-Beck** [comment]
https://github.com/paritytech/parity-bitcoin/pull/555
